author: Steven Zhao # 作者
description: Steven Zhao's blog
keyword: 
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: yanm1ng
gitment_repo: yanm1ng.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics:
# disqus config
disqus_shortname: 

about: 
  banner: ../css/images/banner.png
  avatar: https://avatars0.githubusercontent.com/u/31215923?s=400&u=3b80494435dd9125df88befd4bca0218dda9c182&v=4
  description: "Create A World Filled With Love"
  weibo_username: KillHub
  twitter_username: 01loveslife
  github_username: KillHub
  zhihu_username: KillHub
  douban_username: 
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Social links
  rss: /atom.xml

# 侧边栏
widgets:
  communiation